server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunobergamo/decoder-config-server-repo
          default-label : main
ead:
  configServer:
    username: admin
    password: 'admin'
  serviceRegistry:
    username: admin
    password: 'admin'

eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URL:http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka}
  instance:
    prefer-ip-address: true

